// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShortLynx.Data.Context;

#nullable disable

namespace ShortLynx.Data.PostgreSql.Migrations
{
    [DbContext(typeof(ShortLynxDbContext))]
    partial class ShortLynxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShortLynx.Data.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Prefix");

                    b.HasIndex("UserAccountId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.CustomDomainEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("CustomDomains");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.LinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomDomainId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLinkCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("CustomDomainId");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("UserLinkCodeId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.MagicLinkTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserAccountId");

                    b.ToTable("MagicLinkTokens");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.MembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("AccountId", "UserAccountId")
                        .IsUnique();

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.ShortCodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LinkId")
                        .IsUnique();

                    b.ToTable("ShortCodes");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserLinkCodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOneTimeUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recipient")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LinkId", "UserId")
                        .IsUnique();

                    b.ToTable("UserLinkCodes");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserVisitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserLinkCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserLinkCodeId");

                    b.ToTable("UserVisits");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.VisitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LinkEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<Guid>("ShortCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkEntityId");

                    b.HasIndex("ShortCodeId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.ApiKeyEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShortLynx.Data.Entities.UserAccountEntity", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Account");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.CustomDomainEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShortLynx.Data.Entities.UserAccountEntity", "UserAccount")
                        .WithMany("CustomDomains")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Account");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.LinkEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShortLynx.Data.Entities.ApiKeyEntity", "ApiKey")
                        .WithMany("Links")
                        .HasForeignKey("ApiKeyId");

                    b.HasOne("ShortLynx.Data.Entities.CustomDomainEntity", "CustomDomain")
                        .WithMany()
                        .HasForeignKey("CustomDomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShortLynx.Data.Entities.UserAccountEntity", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ShortLynx.Data.Entities.UserLinkCodeEntity", "UserLinkCode")
                        .WithMany()
                        .HasForeignKey("UserLinkCodeId");

                    b.Navigation("Account");

                    b.Navigation("ApiKey");

                    b.Navigation("CustomDomain");

                    b.Navigation("UserAccount");

                    b.Navigation("UserLinkCode");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.MagicLinkTokenEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.UserAccountEntity", "UserAccount")
                        .WithMany("MagicLinkTokens")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.MembershipEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.AccountEntity", "Account")
                        .WithMany("Memberships")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShortLynx.Data.Entities.UserAccountEntity", "UserAccount")
                        .WithMany("Memberships")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.UserAccountEntity", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.ShortCodeEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.LinkEntity", "Link")
                        .WithOne()
                        .HasForeignKey("ShortLynx.Data.Entities.ShortCodeEntity", "LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserLinkCodeEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.LinkEntity", "Link")
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserVisitEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.UserLinkCodeEntity", "UserLinkCode")
                        .WithMany()
                        .HasForeignKey("UserLinkCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserLinkCode");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.VisitEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.LinkEntity", null)
                        .WithMany("Visits")
                        .HasForeignKey("LinkEntityId");

                    b.HasOne("ShortLynx.Data.Entities.ShortCodeEntity", "ShortCode")
                        .WithMany()
                        .HasForeignKey("ShortCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortCode");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.LinkEntity", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserAccountEntity", b =>
                {
                    b.Navigation("CustomDomains");

                    b.Navigation("MagicLinkTokens");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
