// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShortLynx.Data.Context;

#nullable disable

namespace ShortLynx.Data.PostgreSql.Migrations
{
    [DbContext(typeof(ShortLynxDbContext))]
    partial class ShortLynxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShortLynx.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Prefix");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.LinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLinkCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("UserLinkCodeId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.ShortCodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LinkId")
                        .IsUnique();

                    b.ToTable("ShortCodes");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserLinkCodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOneTimeUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LinkId", "UserId")
                        .IsUnique();

                    b.ToTable("UserLinkCodes");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserVisitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserLinkCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserLinkCodeId");

                    b.ToTable("UserVisits");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.VisitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LinkEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<Guid>("ShortCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkEntityId");

                    b.HasIndex("ShortCodeId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.LinkEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.ApiKeyEntity", "ApiKey")
                        .WithMany("Links")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShortLynx.Data.Entities.UserLinkCodeEntity", "UserLinkCode")
                        .WithMany()
                        .HasForeignKey("UserLinkCodeId");

                    b.Navigation("ApiKey");

                    b.Navigation("UserLinkCode");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.ShortCodeEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.LinkEntity", "Link")
                        .WithOne()
                        .HasForeignKey("ShortLynx.Data.Entities.ShortCodeEntity", "LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserLinkCodeEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.LinkEntity", "Link")
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.UserVisitEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.UserLinkCodeEntity", "UserLinkCode")
                        .WithMany()
                        .HasForeignKey("UserLinkCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserLinkCode");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.VisitEntity", b =>
                {
                    b.HasOne("ShortLynx.Data.Entities.LinkEntity", null)
                        .WithMany("Visits")
                        .HasForeignKey("LinkEntityId");

                    b.HasOne("ShortLynx.Data.Entities.ShortCodeEntity", "ShortCode")
                        .WithMany()
                        .HasForeignKey("ShortCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortCode");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("ShortLynx.Data.Entities.LinkEntity", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
